config/routes.rb
Rails.application.routes.draw do
  resources :boards
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  root "boards#new"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/board.rb
class Board < ApplicationRecord
  validates_presence_of :name, :email
  validates :length, :width, :mines, numericality: { greater_than: 0}
  validate :mines_count
  before_create :populate_state

  private

  def populate_state
    size = length*width
    arr = Array.new(size, 0)
    mines_index = (0...size).to_a.shuffle.take(mines)
    mines_index.each do |i|
      arr[i] = -1
    end
    self.state = arr.each_slice(width)
  end

  def mines_count
    if mines && length && width && mines > length*width
      errors.add(:mines, "can't be greater than total number of cells")
    end
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/boards_controller.rb
class BoardsController < ApplicationController
  before_action :set_board, only: %i[ show edit update destroy ]

  # GET /boards or /boards.json
  def index
    @boards = Board.all
  end

  # GET /boards/1 or /boards/1.json
  def show
  end

  # GET /boards/new
  def new
    @boards = Board.order(created_at: :desc).take(10)
    @board = Board.new
  end

  # POST /boards or /boards.json
  def create
    @board = Board.new(board_params)

    respond_to do |format|
      if @board.save
        format.html { redirect_to board_url(@board), notice: "Board was successfully created." }
        format.json { render :show, status: :created, location: @board }
      else
        @boards = Board.order(created_at: :desc).take(10)
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @board.errors, status: :unprocessable_entity }
      end
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_board
      @board = Board.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def board_params
      params.require(:board).permit(:email, :name, :length, :width, :mines)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/boards_helper.rb
module BoardsHelper
end

app/views/boards/_form.html.erb
<%= form_with(model: board) do |form| %>
  <% if board.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(board.errors.count, "error") %> prohibited this board from being saved:</h2>

      <ul>
        <% board.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="form-group">
    <%= form.label :email, class: "control-label"%>
    <%= form.email_field :email, class: "form-control"%>
  </div>

  <div class="form-group">
    <%= form.label :name, style: "display: block" %>
    <%= form.text_field :name, class: "form-control" %>
  </div>

  <div class="form-group">
    <%= form.label :length, style: "display: block" %>
    <%= form.number_field :length, class: "form-control" %>
  </div>

  <div class="form-group">
    <%= form.label :width, style: "display: block" %>
    <%= form.number_field :width, class: "form-control" %>
  </div>

  <div class="form-group">
    <%= form.label :mines, style: "display: block" %>
    <%= form.number_field :mines, class: "form-control" %>
  </div>

  <div class="form-group mt-2">
    <%= form.submit class: "btn btn-success", value: "Generate Board" %>
  </div>
<% end %>

app/views/boards/_list.html.erb
<table id="boards" class="table">
  <thead>
    <th>Name</th>
    <th>Creator</th>
    <th>Created at</th>
  </thead>
  <tbody>
    <% boards.each do |board| %>
      <tr>
        <td>
          <%= link_to "#{board.name}", board %>
        </td>

        <td>
          <%= board.email %>
        </td>

        <td>
          <%= board.created_at.strftime('%m/%d/%Y %I:%M%p') %>
        </td>
      </tr>
    <% end %>
  </tbody>
</table>

app/views/boards/index.html.erb
<p style="color: green"><%= notice %></p>

<h1>Boards</h1>

<%= render "list", boards: @boards %>

<%= link_to "New board", new_board_path %>

app/views/boards/new.html.erb
<div class="container">
  <h1>Create new board</h1>

  <%= render "form", board: @board %>
</div>

<br>

<div class="container">
  <h3>Recent Boards</h3>  
  <%= render "list", boards: @boards %>
  
  <div>
    <%= link_to "view all generated boards", boards_path %>
  </div>
</div>

app/views/boards/show.html.erb
<p style="color: green"><%= notice %></p>
<div class="container">
  <h3>
    <strong>Board Name:</strong>
    <%= @board.name %>
  </h3>

  <p>
    <strong>Created By:</strong>
    <%= @board.email %>
  </p>

  <p>
    <table style="border: 1px solid black">
      <tbody>
        <% @board.state.each do |row| %>
          <tr>
            <% row.each do |cell| %>
              <td class="p-1">
                <% if cell == 0 %>
                  <i class="fas fa-square" style="color:grey"></i>
                <% else %>
                  <i class="fas fa-bomb"></i>
                <% end %>
              </td>
            <% end %>
          </tr>
        <% end %>
      </tbody>
    </table>
  </p>
</div>


<div>
  <%= link_to "Back to boards", boards_path %>
</div>
<script src="https://kit.fontawesome.com/a076d05399.js" crossorigin="anonymous"></script>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Minesweeper</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <!-- <%= javascript_importmap_tags %> -->
  </head>

  <body>
    <%= yield %>
  </body>
</html>